_Lambda School Data Science, Unit 2_
 
# Sprint Challenge: Predict Steph Curry's shots 🏀

For your Sprint Challenge, you'll use a dataset with all Steph Curry's NBA field goal attempts. (Regular season and playoff games, from October 28, 2009, through June 5, 2019.) 

You'll predict whether each shot was made, using information about the shot and the game. This is hard to predict! Try to get above 60% accuracy. The dataset was collected with the [nba_api](https://github.com/swar/nba_api) Python library.

In [244]:
%%capture
import sys

if 'google.colab' in sys.modules:
    # Install packages in Colab
    !pip install category_encoders==2.*
    !pip install pandas-profiling==2.*

In [245]:
# Read data
import pandas as pd
url = 'https://drive.google.com/uc?export=download&id=1fL7KPyxgGYfQDsuJoBWHIWwCAf-HTFpX'
df = pd.read_csv(url)

# Check data shape
assert df.shape == (13958, 20)

To demonstrate mastery on your Sprint Challenge, do all the required, numbered instructions in this notebook.

To earn a score of "3", also do all the stretch goals.

You are permitted and encouraged to do as much data exploration as you want.

**1. Begin with baselines for classification.** Your target to predict is `shot_made_flag`. What is your baseline accuracy, if you guessed the majority class for every prediction?

**2. Hold out your test set.** Use the 2018-19 season to test. NBA seasons begin in October and end in June. You'll know you've split the data correctly when your test set has 1,709 observations.

**3. Engineer new feature.** Engineer at least **1** new feature, from this list, or your own idea.
- **Homecourt Advantage**: Is the home team (`htm`) the Golden State Warriors (`GSW`) ?
- **Opponent**: Who is the other team playing the Golden State Warriors?
- **Seconds remaining in the period**: Combine minutes remaining with seconds remaining, to get the total number of seconds remaining in the period.
- **Seconds remaining in the game**: Combine period, and seconds remaining in the period, to get the total number of seconds remaining in the game. A basketball game has 4 periods, each 12 minutes long.
- **Made previous shot**: Was Steph Curry's previous shot successful?

**4. Decide how to validate** your model. Choose one of the following options. Any of these options are good. You are not graded on which you choose.
- **Train/validate/test split: train on the 2009-10 season through 2016-17 season, validate with the 2017-18 season.** You'll know you've split the data correctly when your train set has 11,081 observations, and your validation set has 1,168 observations.
- **Train/validate/test split: random 80/20%** train/validate split.
- **Cross-validation** with independent test set. You may use any scikit-learn cross-validation method.

**5.** Use a scikit-learn **pipeline** to **encode categoricals** and fit a **Decision Tree** or **Random Forest** model.

**6.** Get your model's **validation accuracy.** (Multiple times if you try multiple iterations.) 

**7.** Get your model's **test accuracy.** (One time, at the end.)


**8.** Given a **confusion matrix** for a hypothetical binary classification model, **calculate accuracy, precision, and recall.**

### Stretch Goals
- Engineer 4+ new features total, either from the list above, or your own ideas.
- Make 2+ visualizations to explore relationships between features and target.
- Optimize 3+ hyperparameters by trying 10+ "candidates" (possible combinations of hyperparameters). You can use `RandomizedSearchCV` or do it manually.
- Get and plot your model's feature importances.



## 1. Begin with baselines for classification. 

>Your target to predict is `shot_made_flag`. What would your baseline accuracy be, if you guessed the majority class for every prediction?

In [246]:
df.head()

game_id  game_event_id    player_name  period  minutes_remaining  \
0  20900015              4  Stephen Curry       1                 11   
1  20900015             17  Stephen Curry       1                  9   
2  20900015             53  Stephen Curry       1                  6   
3  20900015            141  Stephen Curry       2                  9   
4  20900015            249  Stephen Curry       2                  2   

   seconds_remaining          action_type       shot_type  \
0                 25            Jump Shot  3PT Field Goal   
1                 31  Step Back Jump shot  2PT Field Goal   
2                  2            Jump Shot  2PT Field Goal   
3                 49            Jump Shot  2PT Field Goal   
4                 19            Jump Shot  2PT Field Goal   

         shot_zone_basic         shot_zone_area shot_zone_range  \
0      Above the Break 3  Right Side Center(RC)         24+ ft.   
1              Mid-Range   Left Side Center(LC)       16-24 ft.   
2  In The Paint (Non-RA)              Center(C)        8-16 ft.   
3              Mid-Range           Left Side(L)       16-24 ft.   
4              Mid-Range   Left Side Center(LC)       16-24 ft.   

   shot_distance  loc_x  loc_y  shot_made_flag   game_date  htm  vtm  \
0             26     99    249               0  2009-10-28  GSW  HOU   
1             18   -122    145               1  2009-10-28  GSW  HOU   
2             14    -60    129               0  2009-10-28  GSW  HOU   
3             19   -172     82               0  2009-10-28  GSW  HOU   
4             16    -68    148               0  2009-10-28  GSW  HOU   

      season_type  scoremargin_before_shot  
0  Regular Season                      2.0  
1  Regular Season                      0.0  
2  Regular Season                     -4.0  
3  Regular Season                     -4.0  
4  Regular Season                      0.0

In [247]:
x = df.copy()

unneeded = ['game_id', 'game_event_id', 'player_name']
df1 = x.drop(columns=unneeded)

In [248]:
df1.head()

period  minutes_remaining  seconds_remaining          action_type  \
0       1                 11                 25            Jump Shot   
1       1                  9                 31  Step Back Jump shot   
2       1                  6                  2            Jump Shot   
3       2                  9                 49            Jump Shot   
4       2                  2                 19            Jump Shot   

        shot_type        shot_zone_basic         shot_zone_area  \
0  3PT Field Goal      Above the Break 3  Right Side Center(RC)   
1  2PT Field Goal              Mid-Range   Left Side Center(LC)   
2  2PT Field Goal  In The Paint (Non-RA)              Center(C)   
3  2PT Field Goal              Mid-Range           Left Side(L)   
4  2PT Field Goal              Mid-Range   Left Side Center(LC)   

  shot_zone_range  shot_distance  loc_x  loc_y  shot_made_flag   game_date  \
0         24+ ft.             26     99    249               0  2009-10-28   
1       16-24 ft.             18   -122    145               1  2009-10-28   
2        8-16 ft.             14    -60    129               0  2009-10-28   
3       16-24 ft.             19   -172     82               0  2009-10-28   
4       16-24 ft.             16    -68    148               0  2009-10-28   

   htm  vtm     season_type  scoremargin_before_shot  
0  GSW  HOU  Regular Season                      2.0  
1  GSW  HOU  Regular Season                      0.0  
2  GSW  HOU  Regular Season                     -4.0  
3  GSW  HOU  Regular Season                     -4.0  
4  GSW  HOU  Regular Season                      0.0

In [249]:
df1.dtypes

period                       int64
minutes_remaining            int64
seconds_remaining            int64
action_type                 object
shot_type                   object
shot_zone_basic             object
shot_zone_area              object
shot_zone_range             object
shot_distance                int64
loc_x                        int64
loc_y                        int64
shot_made_flag               int64
game_date                   object
htm                         object
vtm                         object
season_type                 object
scoremargin_before_shot    float64
dtype: object

In [250]:
import pandas as pd
df1['game_date'] = pd.to_datetime(df1['game_date'])
df1 = df1.set_index('game_date')
df1 = df1.sort_index()
df1.head()

period  minutes_remaining  seconds_remaining          action_type  \
game_date                                                                       
2009-10-28       1                 11                 25            Jump Shot   
2009-10-28       1                  9                 31  Step Back Jump shot   
2009-10-28       1                  6                  2            Jump Shot   
2009-10-28       2                  9                 49            Jump Shot   
2009-10-28       2                  2                 19            Jump Shot   

                 shot_type        shot_zone_basic         shot_zone_area  \
game_date                                                                  
2009-10-28  3PT Field Goal      Above the Break 3  Right Side Center(RC)   
2009-10-28  2PT Field Goal              Mid-Range   Left Side Center(LC)   
2009-10-28  2PT Field Goal  In The Paint (Non-RA)              Center(C)   
2009-10-28  2PT Field Goal              Mid-Range           Left Side(L)   
2009-10-28  2PT Field Goal              Mid-Range   Left Side Center(LC)   

           shot_zone_range  shot_distance  loc_x  loc_y  shot_made_flag  htm  \
game_date                                                                      
2009-10-28         24+ ft.             26     99    249               0  GSW   
2009-10-28       16-24 ft.             18   -122    145               1  GSW   
2009-10-28        8-16 ft.             14    -60    129               0  GSW   
2009-10-28       16-24 ft.             19   -172     82               0  GSW   
2009-10-28       16-24 ft.             16    -68    148               0  GSW   

            vtm     season_type  scoremargin_before_shot  
game_date                                                 
2009-10-28  HOU  Regular Season                      2.0  
2009-10-28  HOU  Regular Season                      0.0  
2009-10-28  HOU  Regular Season                     -4.0  
2009-10-28  HOU  Regular Season                     -4.0  
2009-10-28  HOU  Regular Season                      0.0

In [251]:
target = 'shot_made_flag'

## 2. Hold out your test set.

>Use the 2018-19 season to test. NBA seasons begin in October and end in June. You'll know you've split the data correctly when your test set has 1,709 observations.

In [252]:
train = df1['2009-10-28':'2017-06-30']
val = df1['2017-10-15':'2018-06-30']
test = df1['2018-10-15':]
train.shape, val.shape, test.shape

((11081, 16), (1168, 16), (1709, 16))

In [253]:
train_features = train.drop(columns=[target])

numeric_features = train_features.select_dtypes(include='number').columns.tolist()

cardinality = train_features.select_dtypes(exclude='number').nunique()

categorical_features = cardinality[cardinality <= 50].index.tolist()

features = numeric_features + categorical_features

In [254]:
x_train = train[features]
y_train = train[target]
x_val = val[features]
y_val = val[target]
x_test = test[features]
y_pred = test[target]

## 3. Engineer new feature.

>Engineer at least **1** new feature, from this list, or your own idea.
>
>- **Homecourt Advantage**: Is the home team (`htm`) the Golden State Warriors (`GSW`) ?
>- **Opponent**: Who is the other team playing the Golden State Warriors?
>- **Seconds remaining in the period**: Combine minutes remaining with seconds remaining, to get the total number of seconds remaining in the period.
>- **Seconds remaining in the game**: Combine period, and seconds remaining in the period, to get the total number of seconds remaining in the game. A basketball game has 4 periods, each 12 minutes long.
>- **Made previous shot**: Was Steph Curry's previous shot successful?

    

In [255]:
train['home_court_advantage'] = train['htm'] == 'GSW'

C:\Users\Matt\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.


In [256]:
train['home_court_advantage'].value_counts()

False    5569
True     5512
Name: home_court_advantage, dtype: int64

In [257]:
train['shot_made_flag'].value_counts()

0    5842
1    5239
Name: shot_made_flag, dtype: int64

## **4. Decide how to validate** your model. 

>Choose one of the following options. Any of these options are good. You are not graded on which you choose.
>
>- **Train/validate/test split: train on the 2009-10 season through 2016-17 season, validate with the 2017-18 season.** You'll know you've split the data correctly when your train set has 11,081 observations, and your validation set has 1,168 observations.
>- **Train/validate/test split: random 80/20%** train/validate split.
>- **Cross-validation** with independent test set. You may use any scikit-learn cross-validation method.

In [258]:
import category_encoders as ce
import numpy as np
from sklearn.feature_selection import f_regression, SelectKBest, f_classif
from sklearn.impute import SimpleImputer
from sklearn.linear_model import Ridge
from sklearn.model_selection import cross_val_score
from sklearn.pipeline import make_pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import GridSearchCV, RandomizedSearchCV
from sklearn.ensemble import RandomForestRegressor

In [259]:
from scipy.stats import randint, uniform
from sklearn.ensemble import RandomForestClassifier


pipeline = make_pipeline(
    ce.OneHotEncoder(), 
    SimpleImputer(), 
    StandardScaler(), 
    SelectKBest(f_classif), 
    RandomForestClassifier()
)

param_distributions = {
    'simpleimputer__strategy': ['mean', 'median'], 
    'selectkbest__k': range(1, len(x_train.columns)+1), 
}

# If you're on Colab, decrease n_iter & cv parameters
search = RandomizedSearchCV(
    pipeline, 
    param_distributions=param_distributions, 
    n_iter=100, 
    cv=5, 
    verbose=10, 
    return_train_score=True, 
    n_jobs=-1
)

search.fit(x_train, y_train);

C:\Users\Matt\Anaconda3\lib\site-packages\sklearn\model_selection\_search.py:281: UserWarning: The total space of parameters 28 is smaller than n_iter=100. Running 28 iterations. For exhaustive searches, use GridSearchCV.
  % (grid_size, self.n_iter, grid_size), UserWarning)
[Parallel(n_jobs=-1)]: Using backend LokyBackend with 8 concurrent workers.
Fitting 5 folds for each of 28 candidates, totalling 140 fits
[Parallel(n_jobs=-1)]: Done   2 tasks      | elapsed:    2.9s
[Parallel(n_jobs=-1)]: Done   9 tasks      | elapsed:    4.1s
[Parallel(n_jobs=-1)]: Done  16 tasks      | elapsed:    5.3s
[Parallel(n_jobs=-1)]: Done  25 tasks      | elapsed:    7.3s
[Parallel(n_jobs=-1)]: Done  34 tasks      | elapsed:    9.6s
[Parallel(n_jobs=-1)]: Done  45 tasks      | elapsed:   12.8s
[Parallel(n_jobs=-1)]: Done  56 tasks      | elapsed:   15.5s
[Parallel(n_jobs=-1)]: Done  69 tasks      | elapsed:   19.5s
[Parallel(n_jobs=-1)]: Done  82 tasks      | elapsed:   22.5s
[Parallel(n_jobs=-1)]: Done 

## 5. Use a scikit-learn pipeline to encode categoricals and fit a Decision Tree or Random Forest model.

## 6.Get your model's validation accuracy

> (Multiple times if you try multiple iterations.)

In [260]:
print('Best hyperparameters', search.best_params_)
print('Cross-validation MAE', -search.best_score_)
pipeline = search.best_estimator_
print('Validation Accuracy', pipeline.score(x_val, y_val))

Best hyperparameters {'simpleimputer__strategy': 'mean', 'selectkbest__k': 1}
Cross-validation MAE -0.5723316626201538
Validation Accuracy 0.5873287671232876


## 7. Get your model's test accuracy

> (One time, at the end.)

In [261]:
print('Validation Accuracy', pipeline.score(x_test, y_pred))

Validation Accuracy 0.5751901696898771


## 8. Given a confusion matrix, calculate accuracy, precision, and recall.

Imagine this is the confusion matrix for a binary classification model. Use the confusion matrix to calculate the model's accuracy, precision, and recall.

<table>
  <tr>
    <td colspan="2" rowspan="2"></td>
    <td colspan="2">Predicted</td>
  </tr>
  <tr>
    <td>Negative</td>
    <td>Positive</td>
  </tr>
  <tr>
    <td rowspan="2">Actual</td>
    <td>Negative</td>
    <td style="border: solid">85</td>
    <td style="border: solid">58</td>
  </tr>
  <tr>
    <td>Positive</td>
    <td style="border: solid">8</td>
    <td style="border: solid"> 36</td>
  </tr>
</table>

### Calculate accuracy 

In [277]:
total = 85+58+8+36
total_correct = 85+36
print('Our accuracy in the model is equal to', total_correct/total)

Our accuracy in the model is equal to 0.6470588235294118


### Calculate precision

In [275]:
correct_predictions_made_shots = 36
total_made_shots = 8+36
print('Our precision in the model is equal to', correct_predictions_made_shots/total_made_shots)

Our precision in the model is equal to 0.8181818181818182


### Calculate recall

In [276]:
correct_predictions_missed = 85
total_missed_shots = 85+58
print('Our recall in our model is equal to', correct_predictions_missed / total_missed_shots)

Our recall in our model is equal to 0.5944055944055944
